-- Plugins that ship their own highlight groups: blink.cmp, bufferline,
-- gitsigns, mason, flash, trouble, kulala, copilot, lint, todo-comments,
-- grug-far, noice and the legacy nvim-notify groups.

return function(c, hl)
  -- blink.cmp
  hl.BlinkCmpHint({ fg = c.overlay0 })
  hl.BlinkCmpKindText({ fg = c.fg.base })
  hl.BlinkCmpKindMethod({ fg = c.blue })
  hl.BlinkCmpKindFunction({ fg = c.blue })
  hl.BlinkCmpKindConstructor({ fg = c.base0C })
  hl.BlinkCmpKindField({ fg = c.blue })
  hl.BlinkCmpKindVariable({ fg = c.fg.base })
  hl.BlinkCmpKindClass({ fg = c.base09 })
  hl.BlinkCmpKindInterface({ fg = c.base09 })
  hl.BlinkCmpKindModule({ fg = c.base0A })
  hl.BlinkCmpKindProperty({ fg = c.blue })
  hl.BlinkCmpKindUnit({ fg = c.mauve })
  hl.BlinkCmpKindValue({ fg = c.mauve })
  hl.BlinkCmpKindEnum({ fg = c.base09 })
  hl.BlinkCmpKindKeyword({ fg = c.mauve })
  hl.BlinkCmpKindSnippet({ fg = c.base0F })
  hl.BlinkCmpKindConstant({ fg = c.mauve })
  hl.BlinkCmpKindReference({ fg = c.blue })
  hl.BlinkCmpKindColor({ fg = c.base0F })
  hl.BlinkCmpKindFile({ fg = c.blue })
  hl.BlinkCmpKindFolder({ fg = c.blue })
  hl.BlinkCmpKindEvent({ fg = c.mauve })
  hl.BlinkCmpSearch({ fg = c.accent, bold = true })
  hl.BlinkCmpMenuSelection({ fg = c.fg.text, bg = c.surface2, bold = true })

  -- bufferline (nvim-bufferline.lua)
  hl.BufferLine({ fg = c.fg.dim, bg = c.bg.sunken })
  hl.BufferLineBuffer({ fg = c.fg.base, bg = c.bg.raised })
  hl.BufferLineBufferSelected({ fg = c.fg.text, bg = c.bg.base, bold = true })
  hl.BufferLineBufferVisible({ fg = c.fg.dim, bg = c.bg.raised })
  hl.BufferLineTab({ fg = c.fg.dim, bg = c.bg.sunken })
  hl.BufferLineTabSelected({ fg = c.fg.text, bg = c.bg.base, bold = true })
  hl.BufferLineTabSeparator({ fg = c.overlay0, bg = c.bg.sunken })
  hl.BufferLineTabSeparatorSelected({ fg = c.overlay0, bg = c.bg.base })
  hl.BufferLineIndicatorSelected({ fg = c.accent, bg = c.bg.base })
  hl.BufferLineIndicatorVisible({ fg = c.fg.muted, bg = c.bg.raised })
  hl.BufferLineModified({ fg = c.base09 })
  hl.BufferLineModifiedSelected({ fg = c.base09, bg = c.bg.base })
  hl.BufferLineDuplicate({ fg = c.overlay0 })
  hl.BufferLineDuplicateSelected({ fg = c.overlay0, bg = c.bg.base })
  hl.BufferLineDuplicateVisible({ fg = c.overlay0, bg = c.bg.raised })
  hl.BufferLineOffsetSeparator({ fg = c.overlay0 })
  hl.BufferLineSeparator({ fg = c.overlay0, bg = c.bg.sunken })
  hl.BufferLineSeparatorVisible({ fg = c.overlay0, bg = c.bg.raised })
  hl.BufferLineSeparatorSelected({ fg = c.overlay0, bg = c.bg.base })
  hl.BufferLineCloseButton({ fg = c.fg.muted, bg = c.bg.sunken })
  hl.BufferLineCloseButtonSelected({ fg = c.fg.text, bg = c.bg.base })
  hl.BufferLineCloseButtonVisible({ fg = c.fg.dim, bg = c.bg.raised })
  hl.BufferLinePick({ fg = c.accent, bg = c.surface2, bold = true })
  hl.BufferLinePickVisible({ fg = c.accent, bg = c.surface1 })
  hl.BufferLineFill({ bg = c.bg.sunken })

  -- gitsigns
  hl.GitSignsAdd({ fg = c.base0B })
  hl.GitSignsChange({ fg = c.base0A })
  hl.GitSignsDelete({ fg = c.base08 })
  hl.GitSignsTopdelete({ fg = c.base08 })
  hl.GitSignsChanged({ fg = c.base0A })
  hl.GitSignsAddNr({ fg = c.base0B })
  hl.GitSignsChangeNr({ fg = c.base0A })
  hl.GitSignsDeleteNr({ fg = c.base08 })
  hl.GitSignsCurrentLineBlame({ fg = c.fg.muted, italic = true })
  hl.GitSignsAddLn({ bg = c.surface1 })
  hl.GitSignsChangeLn({ bg = c.surface1 })
  hl.GitSignsDeleteLn({ bg = c.surface1 })
  hl.GitSignsCurrentLineBlameLn({ bg = c.bg.line })

  -- mason
  hl.MasonHeader({ fg = c.bg.base, bg = c.accent, bold = true })
  hl.MasonMasonryHeader({ fg = c.bg.base, bg = c.blue, bold = true })
  hl.MasonHighlight({ fg = c.accent, bold = true })
  hl.MasonHighlightBlock({ fg = c.bg.base, bg = c.accent })
  hl.MasonHighlightBlockBold({ fg = c.bg.base, bg = c.accent, bold = true })
  hl.MasonHighlightSecondary({ fg = c.blue })
  hl.MasonHighlightBlockSecondary({ fg = c.bg.base, bg = c.blue })
  hl.MasonHighlightBlockBoldSecondary({ fg = c.bg.base, bg = c.blue, bold = true })
  hl.MasonMasonryHighlightBlock({ fg = c.bg.base, bg = c.blue })
  hl.MasonError({ fg = c.base08 })
  hl.MasonWarning({ fg = c.base09 })
  hl.MasonHeading({ fg = c.fg.text, bold = true })

  -- flash
  hl.FlashBackdrop({ bg = c.bg.overlay })
  hl.FlashCursor({ fg = c.bg.base, bg = c.accent, bold = true })
  hl.FlashLabel({ fg = c.bg.base, bg = c.blue })
  hl.FlashMatch({ fg = c.fg.text, bg = c.surface2, bold = true })
  hl.FlashCurrent({ fg = c.accent, bold = true })

  -- trouble
  hl.TroubleNormal({ fg = c.fg.base, bg = c.bg.raised })
  hl.TroubleNormalNC({ fg = c.fg.muted, bg = c.bg.raised })
  hl.TroubleText({ fg = c.fg.base })
  hl.TroubleFoldIcon({ fg = c.overlay0 })
  hl.TroubleIndent({ fg = c.surface2 })
  hl.TroubleLocation({ fg = c.fg.dim })
  hl.TroubleFile({ fg = c.blue, bold = true })
  hl.TroubleCount({ fg = c.mauve, bg = c.bg.line, bold = true })
  hl.TroubleSource({ fg = c.overlay0, italic = true })
  hl.TroubleCode({ fg = c.fg.dim })
  hl.TroubleTextError({ fg = c.base08 })
  hl.TroubleTextWarning({ fg = c.base09 })
  hl.TroubleTextInformation({ fg = c.blue })
  hl.TroubleTextHint({ fg = c.base0C })
  hl.TroubleIconDirectory({ fg = c.blue })
  hl.TroubleIconFile({ fg = c.fg.base })

  -- kulala
  hl.Kulala({ fg = c.fg.base, bg = c.bg.raised })
  hl.KulalaBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.KulalaTitle({ fg = c.bg.base, bg = c.accent, bold = true })
  hl.KulalaOutputTitle({ fg = c.bg.base, bg = c.blue, bold = true })
  hl.KulalaInfo({ fg = c.blue })
  hl.KulalaSuccess({ fg = c.base0B })
  hl.KulalaWarn({ fg = c.base09 })
  hl.KulalaError({ fg = c.base08 })
  hl.KulalaHint({ fg = c.fg.dim })
  hl.KulalaBullet({ fg = c.accent })
  hl.KulalaKey({ fg = c.mauve })
  hl.KulalaValue({ fg = c.fg.text })
  hl.KulalaHeader({ fg = c.fg.text, bold = true })
  hl.KulalaArrow({ fg = c.overlay0 })
  hl.KulalaCode({ fg = c.base0B })
  hl.KulalaLeftAccent({ fg = c.accent })
  hl.KulalaRightAccent({ fg = c.blue })

  -- copilot / lsp clients
  hl.CopilotHint({ fg = c.overlay0, italic = true })
  hl.CopilotChat({ fg = c.fg.base })
  hl.CopilotChatHeader({ fg = c.accent, bold = true })
  hl.CopilotChatSeparator({ fg = c.overlay0 })
  hl.LspReferenceText({ bg = c.surface1 })
  hl.LspReferenceRead({ bg = c.surface1 })
  hl.LspReferenceTarget({ bg = c.surface2 })
  hl.LspInlayHint({ fg = c.overlay0, bg = c.bg.sunken, italic = true })
  hl.LspCodeLens({ fg = c.overlay0 })
  hl.LspCodeLensSeparator({ fg = c.surface2 })

  -- lint
  hl.Lint({ fg = c.fg.dim })
  hl.LintError({ fg = c.base08 })
  hl.LintErrorInlay({ fg = c.base08 })
  hl.LintWarning({ fg = c.base09 })
  hl.LintWarningInlay({ fg = c.base09 })
  hl.LintInfo({ fg = c.blue })
  hl.LintInfoInlay({ fg = c.blue })
  hl.LintHint({ fg = c.base0C })
  hl.LintHintInlay({ fg = c.base0C })
  hl.LintUnneeded({ fg = c.overlay0 })

  -- todo-comments
  hl.Todo({ fg = c.accent, bold = true })
  hl.TodoFix({ fg = c.base0B })
  hl.TodoTxt({ fg = c.accent, bold = true })
  hl.Commented({ fg = c.fg.dim, bg = "NONE" })
  hl.CommentedDone({ fg = c.fg.dim, bg = "NONE" })

  -- grug-far
  hl.GrugFarHelpHeader({ fg = c.bg.base, bg = c.accent, bold = true })
  hl.GrugFarHelpWin({ fg = c.fg.base, bg = c.bg.raised })
  hl.GrugFarHelpWinBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.GrugFarInputWin({ fg = c.fg.base, bg = c.bg.raised })
  hl.GrugFarInputWinBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.GrugFarResultsWin({ fg = c.fg.base, bg = c.bg.raised })
  hl.GrugFarResultsWinBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.GrugFarResultsCount({ fg = c.fg.dim })
  hl.GrugFarResultsFile({ fg = c.fg.dim })
  hl.GrugFarResultsFolderName({ fg = c.blue, bold = true })
  hl.GrugFarResultsStem({ fg = c.fg.base, bold = true })
  hl.GrugFarResultsNoMatch({ fg = c.overlay0 })
  hl.GrugFarResultsNumber({ fg = c.mauve })
  hl.GrugFarResultsMatch({ fg = c.accent, bold = true })

  -- noice
  hl.NoiceCmdlinePopup({ fg = c.fg.base, bg = c.bg.raised })
  hl.NoiceCmdlinePopupBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.NoiceCmdlinePopupTitle({ fg = c.bg.base, bg = c.accent, bold = true })
  hl.NoiceCmdline({ fg = c.fg.base, bg = c.bg.raised })
  hl.NoiceCmdlineIcon({ fg = c.accent })
  hl.NoiceCmdlineIconSearch({ fg = c.blue })
  hl.NoiceCmdlinePrompt({ fg = c.fg.faint })
  hl.NoiceMini({ fg = c.fg.base, bg = c.bg.base })
  hl.NoicePopup({ fg = c.fg.base, bg = c.bg.raised })
  hl.NoicePopupBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.NoicePopupmenu({ fg = c.fg.base, bg = c.bg.raised })
  hl.NoicePopupmenuBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.NoicePopupmenuMatch({ fg = c.accent, bold = true })
  hl.NoicePopupmenuSelected({ fg = c.fg.text, bg = c.surface2, bold = true })
  hl.NoiceSplit({ fg = c.fg.base, bg = c.bg.base })
  hl.NoiceSplitBorder({ fg = c.overlay0, bg = c.bg.base })
  hl.NoiceVirtualText({ fg = c.overlay0 })

  -- legacy nvim-notify (still read by a few notification fallbacks)
  hl.NotifyERRORBorder({ fg = c.base08, bg = c.bg.raised })
  hl.NotifyWARNBorder({ fg = c.base09, bg = c.bg.raised })
  hl.NotifyINFOBorder({ fg = c.blue, bg = c.bg.raised })
  hl.NotifyDEBUGBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.NotifyTRACEBorder({ fg = c.mauve, bg = c.bg.raised })
  hl.NotifyERRORIcon({ fg = c.base08 })
  hl.NotifyWARNIcon({ fg = c.base09 })
  hl.NotifyINFOIcon({ fg = c.blue })
  hl.NotifyDEBUGIcon({ fg = c.overlay0 })
  hl.NotifyTRACEIcon({ fg = c.mauve })
  hl.NotifyERRORTitle({ fg = c.base08, bold = true })
  hl.NotifyWARNTitle({ fg = c.base09, bold = true })
  hl.NotifyINFOTitle({ fg = c.blue, bold = true })
  hl.NotifyDEBUGTitle({ fg = c.overlay0, bold = true })
  hl.NotifyTRACETitle({ fg = c.mauve, bold = true })
  hl.NotifyERRORBody({ fg = c.fg.base, bg = c.bg.raised })
  hl.NotifyWARNBody({ fg = c.fg.base, bg = c.bg.raised })
  hl.NotifyINFOBody({ fg = c.fg.base, bg = c.bg.raised })
  hl.NotifyDEBUGBody({ fg = c.fg.base, bg = c.bg.raised })
  hl.NotifyTRACEBody({ fg = c.fg.base, bg = c.bg.raised })

  -- mini.nvim bits that are installed here (test, files)
  hl.MiniFilesNormal({ fg = c.fg.base })
  hl.MiniFilesBorder({ fg = c.overlay0 })
  hl.MiniFilesBorderFocused({ fg = c.accent })
  hl.MiniFilesFile({ fg = c.fg.base })
  hl.MiniFilesDirectory({ fg = c.blue })
  hl.MiniFilesTitleFile({ fg = c.fg.text, bg = c.bg.base, bold = true })
  hl.MiniFilesTitleDirectory({ fg = c.fg.text, bg = c.bg.base, bold = true })
  hl.MiniIconsAzure({ fg = c.blue })
  hl.MiniIconsBlue({ fg = c.blue })
  hl.MiniIconsCyan({ fg = c.base0C })
  hl.MiniIconsGreen({ fg = c.base0B })
  hl.MiniIconsGrey({ fg = c.overlay0 })
  hl.MiniIconsOrange({ fg = c.base09 })
  hl.MiniIconsPurple({ fg = c.mauve })
  hl.MiniIconsRed({ fg = c.base08 })
  hl.MiniIconsYellow({ fg = c.base0A })
  hl.MiniIndentscopeSymbol({ fg = c.overlay0 })
  hl.MiniIndentscopePrefix({ nocombine = true })

  -- 0.10+ semantic tokens fallback
  hl["@lsp.type.variable.parameter"]({ fg = c.fg.base, italic = true })
  hl["@lsp.mod.readonly"]({ sp = c.base08 })
  hl["@lsp.typemod.variable.readonly"]({ fg = c.mauve })
end
