-- snacks.nvim: the picker, the file explorer, the dashboard, the notifier and
-- the small widgets (winbar, input, indent, scrollbar, column, quick menu,
-- health). snacks falls back to its own defaults for anything not listed here,
-- so this painter only covers the groups it actually reads.

return function(c, hl)
  -- Picker
  hl.SnacksPicker({ fg = c.fg.base, bg = c.bg.raised })
  hl.SnacksPickerBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.SnacksPickerList({ bg = c.bg.raised })
  hl.SnacksPickerListBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.SnacksPickerTitle({ fg = c.bg.base, bg = c.accent, bold = true })
  hl.SnacksPickerDir({ fg = c.blue, bold = true })
  hl.SnacksPickerFile({ fg = c.fg.base })
  hl.SnacksPickerFolder({ fg = c.blue })
  hl.SnacksPickerExe({ fg = c.base0B, bold = true })
  hl.SnacksPickerLink({ fg = c.mauve })
  hl.SnacksPickerSpecial({ fg = c.base0C })
  hl.SnacksPickerPrompt({ fg = c.fg.faint })
  hl.SnacksPickerSearch({ fg = c.accent, bold = true })
  hl.SnacksPickerSelected({ fg = c.fg.text, bg = c.surface2, bold = true })
  hl.SnacksPickerSelectedBorder({ fg = c.accent, bg = c.surface2 })
  hl.SnacksPickerMatch({ fg = c.accent, bold = true })
  hl.SnacksPickerPreview({ bg = c.bg.raised })
  hl.SnacksPickerPreviewBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.SnacksPickerPreviewTitle({ fg = c.bg.base, bg = c.mauve, bold = true })
  hl.SnacksPickerHelp({ fg = c.fg.muted })
  hl.SnacksPickerInputBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.SnacksPickerInputTitle({ fg = c.bg.base, bg = c.accent, bold = true })
  hl.SnacksPickerTab({ fg = c.fg.muted })
  hl.SnacksPickerTabActive({ fg = c.fg.text, bg = c.surface2, bold = true })
  hl.SnacksPickerTabSep({ fg = c.overlay0 })

  -- Explorer: snacks 2.x folds the explorer into the picker, so it paints
  -- through SnacksPicker* groups; the old SnacksExplorer* names are gone.
  -- Tree = the indent column in the file tree, ListCursorLine = the selection.
  hl.SnacksPickerTree({ fg = c.surface2 })
  hl.SnacksPickerListCursorLine({ fg = c.fg.text, bg = c.surface2, bold = true })
  hl.SnacksPickerPreviewCursorLine({ bg = c.bg.line })

  -- Dashboard
  hl.SnacksDashboard({ fg = c.fg.base, bg = c.bg.base })
  hl.SnacksDashboardHeader({ fg = c.fg.text, bg = c.bg.base, bold = true })
  hl.SnacksDashboardFooter({ fg = c.fg.muted, bg = c.bg.base })
  hl.SnacksDashboardKey({ fg = c.mauve })
  hl.SnacksDashboardDesc({ fg = c.fg.base })
  hl.SnacksDashboardIcon({ fg = c.blue })
  hl.SnacksDashboardTitle({ fg = c.accent, bold = true })
  hl.SnacksDashboardLogo({ fg = c.accent })
  hl.SnacksDashboardSpecial({ fg = c.base0C })
  hl.SnacksDashboardCode({ fg = c.mauve })
  hl.SnacksDashboardMruTitle({ fg = c.fg.dim, bold = true })
  hl.SnacksDashboardMruIcon({ fg = c.blue })
  hl.SnacksDashboardMru({ fg = c.fg.base })
  hl.SnacksDashboardProjectTitle({ fg = c.fg.dim, bold = true })
  hl.SnacksDashboardProjectIcon({ fg = c.base0B })
  hl.SnacksDashboardProject({ fg = c.fg.base })
  hl.SnacksDashboardFull({ fg = c.fg.base })
  hl.SnacksDashboardDisabled({ fg = c.overlay0 })
  hl.SnacksDashboardShortcut({ fg = c.fg.muted })

  -- Notifier
  hl.SnacksNotifier({ fg = c.fg.base, bg = c.bg.raised })
  hl.SnacksNotifierBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.SnacksNotifierTitle({ fg = c.bg.base, bg = c.accent, bold = true })
  hl.SnacksNotifierBody({ fg = c.fg.base, bg = c.bg.raised })
  hl.SnacksNotifierIcon({ fg = c.accent })
  hl.SnacksNotifierIconInfo({ fg = c.blue })
  hl.SnacksNotifierIconWarn({ fg = c.base09 })
  hl.SnacksNotifierIconError({ fg = c.base08 })
  hl.SnacksNotifierIconSuccess({ fg = c.base0B })
  hl.SnacksNotifierIconLoading({ fg = c.mauve })

  -- Widgets
  hl.SnacksWinbar({ fg = c.fg.dim, bg = c.bg.sunken })
  hl.SnacksWinbarFile({ fg = c.fg.base, bg = c.bg.sunken, bold = true })
  hl.SnacksWinbarDir({ fg = c.fg.muted, bg = c.bg.sunken })
  hl.SnacksWinbarSeparator({ fg = c.overlay0, bg = c.bg.sunken })
  hl.SnacksWinbarFileIcon({ fg = c.accent, bg = c.bg.sunken })
  hl.SnacksInput({ fg = c.fg.base, bg = c.bg.raised })
  hl.SnacksInputBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.SnacksInputTitle({ fg = c.bg.base, bg = c.accent, bold = true })
  hl.SnacksInputIcon({ fg = c.accent })
  hl.SnacksInputLabel({ fg = c.fg.dim })
  hl.SnacksIndent({ fg = c.surface2 })
  hl.SnacksIndentDot({ fg = c.overlay0 })
  hl.SnacksIndentLineActive({ fg = c.fg.dim })
  hl.SnacksIndentModule({ fg = c.overlay0 })
  hl.SnacksScrollbar({ bg = c.bg.raised })
  hl.SnacksScrollbarThumb({ bg = c.overlay0 })
  hl.SnacksScrollbarThumbHover({ bg = c.overlay1 })
  hl.SnacksScrollbarTrack({ bg = c.bg.sunken })
  hl.SnacksColumn({ bg = c.bg.raised })
  hl.SnacksQuickMenu({ fg = c.fg.base, bg = c.bg.raised })
  hl.SnacksQuickMenuBorder({ fg = c.overlay0, bg = c.bg.raised })
  hl.SnacksQuickMenuTitle({ fg = c.bg.base, bg = c.accent, bold = true })
  hl.SnacksHealthTitle({ fg = c.accent, bold = true })
  hl.SnacksHealthError({ fg = c.base08, bold = true })
  hl.SnacksHealthWarn({ fg = c.base09, bold = true })
  hl.SnacksHealthInfo({ fg = c.blue })
  hl.SnacksHealthHelp({ fg = c.fg.muted })
  hl.SnacksHealthHint({ fg = c.fg.muted })
  hl.SnacksHealthProgressDone({ fg = c.accent, bold = true })
  hl.SnacksHealthProgressTodo({ fg = c.overlay0 })
  hl.SnacksDashboardSearchCount({ fg = c.fg.muted })
  hl.SnacksImage({ fg = c.fg.base })
  hl.SnacksImageNormal({ fg = c.fg.base })
  hl.SnacksImageDirty({ fg = c.base09 })
  hl.SnacksImageSpinner({ fg = c.accent })
  hl.SnacksImageSpinnerActive({ fg = c.accent, bold = true })
end
