-- Syntax highlighting: the legacy `syntax` groups, the treesitter captures and the
-- `@lsp.*` semantic groups.
--
-- Treesitter highlighting is disabled in this config (see
-- lua/plugins/treesitter.lua), but the captures are still painted so that
-- treesitter-conceal, treesitter-context and the `nvim-treesitter` highlight
-- module look right if they are ever switched on for a single buffer.

return function(c, hl)
  -- Legacy syntax groups, kept in step with the captures below.
  --
  -- Comments take a dim colour from the foreground ramp, never one from the
  -- overlay/background ramp (those read as a tinted block rather than as text),
  -- and `bg = "NONE"` stops anything else painting behind them.
  hl.Comment({ fg = c.fg.dim, italic = true, bg = "NONE" })
  hl.SpecialComment({ fg = c.fg.base, bold = true, italic = true, bg = "NONE" })
  hl.Constant({ fg = c.mauve })
  hl.String({ fg = c.base0B })
  hl.Character({ fg = c.base0B })
  hl.Number({ fg = c.mauve, bold = true })
  hl.Boolean({ fg = c.mauve, bold = true })
  hl.Float({ fg = c.mauve, bold = true })
  hl.Identifier({ fg = c.fg.base })
  hl.Function({ fg = c.blue })
  hl.Identifier({ fg = c.fg.base })
  hl.Statement({ fg = c.mauve })
  hl.Conditional({ fg = c.mauve })
  hl.Repeat({ fg = c.mauve })
  hl.Label({ fg = c.mauve })
  hl.Operator({ fg = c.mauve })
  hl.Keyword({ fg = c.mauve })
  hl.Exception({ fg = c.mauve })
  hl.PreProc({ fg = c.base0C })
  hl.Include({ fg = c.base0C })
  hl.Define({ fg = c.base0C })
  hl.Macro({ fg = c.base0C })
  hl.PreCondit({ fg = c.base0C })
  hl.Type({ fg = c.base09 })
  hl.Structure({ fg = c.base09 })
  hl.Class({ fg = c.base09 })
  hl.Enum({ fg = c.base09 })
  hl.Typedef({ fg = c.base09 })
  hl.Special({ fg = c.base0F })
  hl.SpecialChar({ fg = c.base0F })
  hl.Tag({ fg = c.base0A })
  hl.Delimiter({ fg = c.overlay0 })
  hl.Debug({ fg = c.base08 })
  hl.Underlined({ underline = true })
  hl.Bold({ bold = true })
  hl.Italic({ italic = true })
  hl.ignore({ fg = c.fg.base })

  -- Treesitter captures
  hl["@variable"]({ fg = c.fg.base })
  hl["@variable.builtin"]({ fg = c.blue, italic = true })
  hl["@variable.parameter"]({ fg = c.fg.base, italic = true })
  hl["@variable.member"]({ fg = c.blue })
  hl["@constant"]({ fg = c.mauve })
  hl["@constant.builtin"]({ fg = c.mauve, italic = true })
  hl["@constant.macro"]({ fg = c.base0C })
  hl["@module"]({ fg = c.base0A })
  hl["@label"]({ fg = c.fg.text })
  hl["@string"]({ fg = c.base0B })
  hl["@string.documentation"]({ fg = c.base0B, italic = true })
  hl["@string.regexp"]({ fg = c.base0F })
  hl["@string.escape"]({ fg = c.base0F })
  hl["@string.special"]({ fg = c.base0F })
  hl["@character"]({ fg = c.base0B })
  hl["@boolean"]({ fg = c.mauve, bold = true })
  hl["@number"]({ fg = c.mauve, bold = true })
  hl["@number.float"]({ fg = c.mauve, bold = true })
  hl["@type"]({ fg = c.base09 })
  hl["@type.builtin"]({ fg = c.base09, italic = true })
  hl["@type.definition"]({ fg = c.base09 })
  hl["@attribute"]({ fg = c.blue })
  hl["@attribute.builtin"]({ fg = c.blue, italic = true })
  hl["@property"]({ fg = c.blue })
  hl["@function"]({ fg = c.blue })
  hl["@function.builtin"]({ fg = c.blue, italic = true })
  hl["@function.call"]({ fg = c.blue })
  hl["@function.macro"]({ fg = c.base0C })
  hl["@function.method"]({ fg = c.blue })
  hl["@constructor"]({ fg = c.base0C })
  hl["@operator"]({ fg = c.mauve })
  hl["@keyword"]({ fg = c.mauve })
  hl["@keyword.conditional"]({ fg = c.mauve })
  hl["@keyword.repeat"]({ fg = c.mauve })
  hl["@keyword.return"]({ fg = c.mauve })
  hl["@keyword.exception"]({ fg = c.mauve })
  hl["@keyword.function"]({ fg = c.mauve })
  hl["@keyword.operator"]({ fg = c.mauve })
  hl["@keyword.import"]({ fg = c.base0C })
  hl["@keyword.modifier"]({ fg = c.mauve })
  hl["@punctuation.delimiter"]({ fg = c.overlay0 })
  hl["@punctuation.bracket"]({ fg = c.overlay0 })
  hl["@punctuation.special"]({ fg = c.blue })
  hl["@comment"]({ fg = c.fg.dim, italic = true, bg = "NONE" })
  hl["@comment.error"]({ fg = c.base08, bold = true, bg = "NONE" })
  hl["@comment.warning"]({ fg = c.base09, bold = true, bg = "NONE" })
  hl["@comment.todo"]({ fg = c.accent, bold = true, bg = "NONE" })
  hl["@comment.note"]({ fg = c.blue, bold = true, bg = "NONE" })
  hl["@markup.strong"]({ bold = true })
  hl["@markup.italic"]({ italic = true })
  hl["@markup.underline"]({ underline = true })
  hl["@markup.heading"]({ fg = c.accent, bold = true })
  hl["@markup.quote"]({ fg = c.overlay1, italic = true })
  hl["@markup.math"]({ fg = c.base0C })
  hl["@markup.link"]({ fg = c.blue, underline = true })
  hl["@markup.link.label"]({ fg = c.blue })
  hl["@markup.link.url"]({ fg = c.base0C, italic = true })
  hl["@markup.raw"]({ fg = c.base0C })
  hl["@markup.list"]({ fg = c.blue })
  hl["@markup.list.checked"]({ fg = c.base0B })
  hl["@markup.list.unchecked"]({ fg = c.overlay0 })
  hl["@diff.plus"]({ fg = c.base0B })
  hl["@diff.minus"]({ fg = c.base08 })
  hl["@diff.delta"]({ fg = c.base09 })
  hl["@tag"]({ fg = c.base0A })
  hl["@tag.attribute"]({ fg = c.base09 })
  hl["@tag.delimiter"]({ fg = c.overlay0 })

  -- LSP semantic tokens
  hl["@lsp.type.class"]({ fg = c.base09 })
  hl["@lsp.type.comment"]({ fg = c.fg.dim, italic = true, bg = "NONE" })
  hl["@lsp.type.decorator"]({ fg = c.blue })
  hl["@lsp.type.enum"]({ fg = c.base09 })
  hl["@lsp.type.enumMember"]({ fg = c.mauve })
  hl["@lsp.type.function"]({ fg = c.blue })
  hl["@lsp.type.interface"]({ fg = c.base09 })
  hl["@lsp.type.macro"]({ fg = c.base0C })
  hl["@lsp.type.method"]({ fg = c.blue })
  hl["@lsp.type.modifier"]({ fg = c.mauve })
  hl["@lsp.type.namespace"]({ fg = c.base0A })
  hl["@lsp.type.number"]({ fg = c.mauve })
  hl["@lsp.type.operator"]({ fg = c.mauve })
  hl["@lsp.type.parameter"]({ fg = c.fg.base, italic = true })
  hl["@lsp.type.property"]({ fg = c.blue })
  hl["@lsp.type.regexp"]({ fg = c.base0F })
  hl["@lsp.type.selfKeyword"]({ fg = c.mauve, italic = true })
  hl["@lsp.type.typeAlias"]({ fg = c.base0C })
  hl["@lsp.type.typeParameter"]({ fg = c.base0C, italic = true })
  hl["@lsp.type.unresolvedReference"]({ fg = c.base0F, underline = true })
  hl["@lsp.type.variable"]({})
  hl["@lsp.type.variable.builtin"]({ fg = c.blue, italic = true })
  hl["@lsp.typemod.function.defaultLibrary"]({ fg = c.blue, italic = true })
  hl["@lsp.typemod.variable.defaultLibrary"]({ fg = c.blue, italic = true })
  hl["@lsp.typemod.variable.readonly"]({ fg = c.mauve })
  hl["@lsp.typemod.variable.builtin"]({ fg = c.blue, italic = true })
  hl["@lsp.typemod.function.async"]({ fg = c.blue, italic = true })
  hl["@lsp.typemod.variable.mutable"]({ fg = c.mauve })
  hl["@lsp.typemod.keyword.async"]({ fg = c.mauve, italic = true })
end
