# Custom packages, that can be defined similarly to ones from nixpkgs
# You can build them using 'nix build .#example'
{ pkgs, inputs, ... }: {
  # example = pkgs.callPackage ./example { };
  user-packages = with pkgs; [
    # GUI Applications
    adi1090x-plymouth-themes
    appimage-run
    arduino-ide
    brave
    catppuccin-cursors.macchiatoLight
    catppuccin-kvantum
    catppuccin-papirus-folders
    code-cursor
    firefox
    gamescope
    genymotion
    kdePackages.bluedevil
    kdePackages.bluez-qt
    kdePackages.dragon
    kdePackages.flatpak-kcm
    kdePackages.kate
    kdePackages.kpmcore
    kdePackages.kwallet-pam
    kdePackages.plasma-nm
    kdePackages.plasma-pa
    kdePackages.plymouth-kcm
    kdePackages.qtstyleplugin-kvantum
    kdePackages.sddm-kcm
    kdePackages.yakuake
    keepassxc
    kitty
    lact
    lutris
    networkmanagerapplet
    nexusmods-app
    nur.repos.mikilio.ttf-ms-fonts
    nur.repos.shadowrz.klassy-qt6
    papirus-folders
    popcorntime
    protonvpn-gui
    qbittorrent
    syncthingtray
    terminus_font
    thunderbird
    times-newer-roman
    ungoogled-chromium
    vesktop
    viber
    virt-manager
    vscodium
    webcord-vencord
    winboat
    wineWowPackages.full
    inputs.zen-browser.packages."x86_64-linux".default
    adwaita-icon-theme
    zellij
    hollywood
    kicad-small
    python3
    python3Packages.pip
    cairo
    ags
    waybar
    waypaper
    copyq
    avizo
    rofi
    swww
    networkmanager_dmenu
    networkmanager
    direnv
    mangohud
    hyprpanel
    libgtop
    bluez
    bluez-tools
    dart-sass
    gvfs
    pcmanfm
    hyprlock
    hyprprop
    hyprnome
    hyprpolkitagent
    hyprsunset
    grim
    hypridle
    hyprlandPlugins.hyprgrass
    inputs.caelestia-shell.packages.${pkgs.system}.with-cli

    # TUI Applications
    alsa-utils
    amdgpu_top
    auto-cpufreq
    bat
    brightnessctl
    busybox
    btop
    cargo
    cpufrequtils
    curl
    distrobox
    docker-compose
    eza
    ffmpeg
    fish
    freerdp
    fzf
    gemini-cli
    git
    gnirehtet
    gnumake
    jre
    kbd
    killall
    lazydocker
    lazygit
    lm_sensors
    mesa-demos
    mpv
    neovim
    ninja
    nodejs
    ntfs3g
    oh-my-zsh
    ollama
    opencode
    p7zip
    pciutils
    powertop
    speechd
    steam-run
    swayidle
    syncthing
    tgpt
    thermald
    tlp
    tmux
    unzip
    upower
    util-linux
    vim
    vimPlugins.nvchad
    wget
    wl-clipboard
    xclip
    zoxide
    zsh
    octaveFull
    picocom
    screen
  ];
  system-packages = with pkgs; [
    # Libraries & Dependencies
    fuse3
    automake
    cmake
    gcc
    gdb
    binutils
    bintools
    coreutils-full
    dxvk
    glibc
    glibc.dev
    icu77
    libgcc
    libgccjit
    libvirt
    libxkbcommon
    luarocks
    eglexternalplatform
    egl-wayland
    libGL
    libva
    libvdpau
    libvdpau-va-gl
    nil
    pkg-config
    radeontop
    virglrenderer
    virtiofsd
    vkd3d
    vkd3d-proton
    vulkan-loader
    vulkan-tools
    vulkan-validation-layers
    vulkan-hdr-layer-kwin6
    zlib
    arduino-cli
    dnsmasq
    flatpak
    fprintd
    libnotify
    pulseaudio
    spice
    spice-gtk
    spice-vdagent
    speechd
    terminus_font
  ];
}