# Custom packages, that can be defined similarly to ones from nixpkgs
# You can build them using 'nix build .#example'
{ pkgs, inputs, ... }:
{
  # example = pkgs.callPackage ./example { };
  user-packages = with pkgs; [
    # GUI Applications
    ags
    arduino-ide
    avizo
    brave
    copyq
    firefox
    genymotion
    heroic
    hyprlock
    hyprpanel
    hyprpolkitagent
    inputs.zen-browser.packages."x86_64-linux".default
    kdePackages.bluedevil
    kdePackages.bluez-qt
    kdePackages.dragon
    kdePackages.flatpak-kcm
    kdePackages.kate
    kdePackages.kpmcore
    kdePackages.okular
    kdePackages.plasma-nm
    kdePackages.plasma-pa
    kdePackages.plymouth-kcm
    kdePackages.sddm-kcm
    kdePackages.yakuake
    keepassxc
    kicad-small
    kitty
    lact
    lutris
    networkmanagerapplet
    nexusmods-app
    pcmanfm
    popcorntime
    protonvpn-gui
    qbittorrent
    qutebrowser
    rofi
    syncthingtray
    thunderbird
    ungoogled-chromium
    vesktop
    viber
    virt-manager
    vscode-fhs
    waybar
    waypaper
    webcord-vencord
    winboat
    wpsoffice

    # TUI Applications
    alsa-utils
    amdgpu_top
    auto-cpufreq
    bat
    brightnessctl
    busybox
    btop
    cargo
    cpufrequtils
    curl
    direnv
    distrobox
    docker-compose
    eza
    ffmpeg
    fish
    freerdp
    fzf
    gemini-cli
    git
    gnirehtet
    gnumake
    grim
    hollywood
    inputs.caelestia-shell.packages.${pkgs.system}.with-cli
    jre
    kbd
    killall
    lazydocker
    lazygit
    lm_sensors
    mesa-demos
    mpv
    neovim
    networkmanager
    networkmanager_dmenu
    ninja
    nodejs
    ntfs3g
    octaveFull
    oh-my-zsh
    ollama
    opencode
    p7zip
    pciutils
    picocom
    powertop
    screen
    speechd
    steam-run
    swww
    swayidle
    syncthing
    tgpt
    thermald
    tlp
    tmux
    unzip
    upower
    util-linux
    vim
    vimPlugins.nvchad
    wget
    wl-clipboard
    xclip
    zellij
    zoxide
    zsh

    # Dependencies
    bluez
    bluez-tools
    cairo
    dart-sass
    gvfs
    libgtop
    mangohud
    python3
    python3Packages.pip
    wineWowPackages.full

    # Utilities
    adwaita-icon-theme
    adi1090x-plymouth-themes
    appimage-run
    catppuccin-cursors.macchiatoLight
    catppuccin-kvantum
    catppuccin-papirus-folders
    code-cursor-fhs
    gamescope
    hypridle
    hyprlandPlugins.hyprgrass
    hyprlandPlugins.hyprscrolling
    hyprnome
    hyprprop
    hyprsunset
    nur.repos.mikilio.ttf-ms-fonts
    nur.repos.shadowrz.klassy-qt6
    papirus-folders
    terminus_font
    times-newer-roman
  ];
  system-packages = with pkgs; [
    # Libraries & Dependencies
    fuse3
    automake
    cmake
    gcc
    gdb
    binutils
    bintools
    coreutils-full
    dxvk
    glibc
    glibc.dev
    icu77
    libgcc
    libgccjit
    libvirt
    libxkbcommon
    luarocks
    eglexternalplatform
    egl-wayland
    libGL
    libva
    libvdpau
    libvdpau-va-gl
    nil
    pkg-config
    radeontop
    virglrenderer
    virtiofsd
    vkd3d
    vkd3d-proton
    vulkan-loader
    vulkan-tools
    vulkan-validation-layers
    vulkan-hdr-layer-kwin6
    zlib
    arduino-cli
    dnsmasq
    flatpak
    fprintd
    libnotify
    pulseaudio
    spice
    spice-gtk
    spice-vdagent
    speechd
    terminus_font
    nh
    nix-output-monitor
    nixfmt
    nixfmt-tree
    lohit-fonts.devanagari
    nix-ld
    stdenv.cc.cc.lib   
    libglvnd
    nvd
  ];
}
