{
  config,
  lib,
  pkgs,
  ...
}:
let
  zshDir = "${config.xdg.configHome}/zsh";

  # Powerlevel10k is not packaged in nixpkgs and has no flake.nix, so pin it
  # directly from GitHub. Rev/hash locked so the build stays pure + reproducible.
  powerlevel10k = pkgs.fetchFromGitHub {
    owner = "romkatv";
    repo = "powerlevel10k";
    rev = "3308262dfbd743b6e1d3956a2b5572f7a049d692";
    hash = "sha256-s0FLaSZdhMTJyHQFtkQWdp0Qi2QAZvy4H40r1FdEOvY=";
  };
in
{
  programs.zsh = {
    enable = true;
    enableCompletion = true;
    autosuggestion.enable = true;
    syntaxHighlighting.enable = true;
    dotDir = zshDir;

    # oh-my-zsh from nixpkgs (replaces the old manual ~/.config/zsh/ohmyzsh clone).
    # autosuggestion + syntax-highlighting are handled natively above, so only the
    # remaining plugins are declared here. POWERLEVEL10K is loaded separately below
    # (it is not packaged in nixpkgs), so the oh-my-zsh theme is just a fallback.
    oh-my-zsh = {
      enable = true;
      plugins = [
        "git"
        "sudo"
        "vi-mode"
      ];
      theme = "robbyrussell";
    };

    # Everything custom (exports, aliases, functions, zoxide, p10k + secrets source)
    # comes from the tracked zshrc.custom file. Its default order (1000) runs after
    # the oh-my-zsh init block (800), so p10k overrides the prompt correctly.
    initContent = lib.mkOrder 1000 (builtins.readFile ./zshrc.custom);
  };

  # fzf + keybindings (Ctrl-T files, Alt-C cd, Ctrl-R history) via zsh integration.
  # The old manual `source fzf/fzf.zsh` in zshrc.custom is now a no-op.
  programs.fzf = {
    enable = true;
    enableZshIntegration = true;
  };
  # Writes FZF_DEFAULT_OPTS_FILE from the global catppuccin flavor (macchiato).
  catppuccin.fzf.enable = true;

  # Powerlevel10k theme (pinned fetchFromGitHub, replaces the manual clone).
  home.file."${zshDir}/powerlevel10k".source = powerlevel10k;

  # Powerlevel10k user config (generated by `p10k configure`).
  home.file."${zshDir}/.p10k.zsh".source = ./p10k.zsh;
}
