{
  pkgs,
  inputs,
  lib,
  ...
}:
let
  nixLinkedPlugins = {
    "AckslD/nvim-neoclip.lua" = {
      package = "nvim-neoclip-lua";
    };
    "kkharji/sqlite.lua" = {
      package = "sqlite-lua";
    };
    "nvim-telescope/telescope.nvim" = {
      package = "telescope-nvim";
    };
    "folke/base16-nvim" = {
      package = "base16-nvim";
    };
    # LazyVim v16 defaults to blink.cmp; the module only tracks it through the
    # coding.blink extra, so it is not in the dev path either.
    "saghen/blink.cmp" = {
      package = "blink-cmp";
    };
    "saghen/blink-copilot" = {
      package = "blink-copilot";
    };
    "catppuccin/nvim" = {
      package = "catppuccin-nvim";
      name = "catppuccin";
    };
    "MeanderingProgrammer/render-markdown.nvim" = {
      package = "render-markdown-nvim";
    };
    "rafamadriz/friendly-snippets" = {
      package = "friendly-snippets";
    };
  };
in
{
  imports = [ inputs.lazyvim.homeManagerModules.default ];

  programs.lazyvim = {
    enable = true;

    pluginSource = "nixpkgs";

    configFiles = ./src/nvim;

    extras = {
      ai.copilot.enable = true;
      ai.copilot-chat.enable = true;
      lang.markdown.enable = true;
      lang.nix.enable = true;
    };

    treesitterParsers = with pkgs.vimPlugins.nvim-treesitter-parsers; [
      cmake
      css
      fish
      git_config
      git_rebase
      gitattributes
      gitcommit
      gitignore
      graphql
      # also highlights kulala's http/rest buffers; kulala cannot install its
      # own parser here, see src/nvim/lua/plugins/kulala.lua
      http
      hyprlang
      rasi
    ];

    extraPackages = with pkgs; [
      copilot-language-server
      # octo.nvim shells out to gh for graphql/pickers
      gh
      lua-language-server
      nixd
      nixfmt
      statix
      stylua
      vscode-langservers-extracted
    ];
  };

  xdg.configFile."nvim/lua/theme".source = ./src/nvim/lua/theme;
  # The LazyVim module only deploys lua/config/{keymaps,options,autocmds}.lua out
  # of configFiles, so any other lua/config module needs an explicit link.
  xdg.configFile."nvim/lua/config/terminals.lua".source = ./src/nvim/lua/config/terminals.lua;

  home.activation.nvimPruneStaleConfig =
    lib.hm.dag.entryAfter
      [
        "writeBoundary"
      ]
      ''
        if [[ -L "$HOME/.config/nvim/lua/theme.lua" ]]; then
          $DRY_RUN_CMD rm -f "$HOME/.config/nvim/lua/theme.lua"
          echo "removed stale nvim theme.lua (superseded by the theme/ directory)"
        fi
        for dir in "$HOME/.config/nvim/lua" "$HOME/.config/nvim/colors"; do
          [[ -d "$dir" ]] || continue
          # A NUL delimiter keeps the read safe for odd file names, and the
          # $'\\0' form is used because two single quotes in a row would close
          # this Nix indented string.
          while IFS= read -r -d $'\0' f; do
            $DRY_RUN_CMD rm -f "$f"
            echo "removed stale nvim config file: $f"
          done < <(find "$dir" -type f -print0)
        done
      '';

  stylix.targets.neovim.enable = false;

  home.packages = lib.mkDefault [
    pkgs.stylua
    pkgs.lua-language-server
    pkgs.sqlite
  ];

  xdg.configFile."nvim/lua/config/nix.lua" = {
    text = ''
      -- Generated by modules/home/config/modules/nvim.
      return {
        sqlite_clib = "${lib.getLib pkgs.sqlite}/lib/libsqlite3.so.0";
      }
    '';
  };

  xdg.configFile."nvim/lua/plugins/zz-nixpkgs.lua" = {
    text = ''
      -- Generated by modules/home/config/modules/nvim. Sorted last so it merges
      -- after the hand-written spec files, which only add opts/keys on top of
      -- `dir`.
      return {
      ${lib.concatStringsSep "\n" (
        map (
          repo:
          let
            entry = nixLinkedPlugins.${repo};
            name = lib.optionalString (entry ? name) ", name = \"${entry.name}\"";
          in
          "  { \"${repo}\"${name}, dir = \"${pkgs.vimPlugins.${entry.package}}\" },"
        ) (lib.attrNames nixLinkedPlugins)
      )}
      }
    '';
  };
}
