{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (lib) mkOption types mkIf;

  # Shared theme database + resolvers (see themes.nix).
  t = import ./themes.nix { inherit lib; };
  inherit (t) themes resolve toBase16;
  sel = t.readSelection ./selection;

  # Build the full machine-readable themes JSON the CLI consumes.
  themesJSON = lib.mapAttrs (_: x: {
    title = x.title;
    flavors = lib.mapAttrs (_: v: {
      title = v.title;
      polarity = v.polarity;
      inherit (v)
        base
        mantle
        crust
        surface0
        surface1
        surface2
        overlay0
        overlay1
        overlay2
        subtext0
        subtext1
        text
        ;
      accents = v.accents;
      ansi = v.ansi;
    }) x.flavors;
  }) themes;

  # ---------------------------------------------------------------------------
  # Default selection: what a fresh build themes terminals/desktop to. This is
  # derived from the tracked `./selection` file, which scripts/theme updates on
  # every switch, so Stylix + the runtime files always follow the active theme.
  # ---------------------------------------------------------------------------
  defaultTheme = sel.themeName;
  defaultFlavor = sel.flavorName;
  defaultAccent = sel.accentName;

  selectedTheme = themes.${defaultTheme};
  selectedFlavor = selectedTheme.flavors.${defaultFlavor};
  r = resolve selectedFlavor defaultAccent;

  h = v: "#${v}";

  # --- kitty runtime theme file ----------------------------------------------
  kittyTheme = ''
    # Generated by modules/config/colors (default) / scripts/theme (runtime).
    # Theme: ${defaultTheme} / ${defaultFlavor} / ${defaultAccent}
    background ${h r.crust}
    foreground ${h r.text}
    selection_background ${h r.accent}
    selection_foreground ${h r.crust}
    url_color ${h r.accent}
    active_border_color ${h r.accent}
    inactive_border_color ${h r.overlay1}
    active_tab_foreground ${h r.crust}
    active_tab_background ${h r.accent}
    inactive_tab_foreground ${h r.text}
    inactive_tab_background ${h r.mantle}
    tab_bar_background ${h r.crust}
    ${lib.concatStringsSep "\n" (lib.imap0 (i: cV: "color${toString i} ${h cV}") r.ansi)}
  '';

  # --- alacritty runtime theme file (a [colors] fragment to import) ----------
  alacrittyTheme = ''
    # Generated by modules/config/colors (default) / scripts/theme (runtime).
    # Theme: ${defaultTheme} / ${defaultFlavor} / ${defaultAccent}
    [colors]
    primary = { background = "${h r.crust}", foreground = "${h r.text}" }
    cursor = { text = "${h r.crust}", cursor = "${h r.accent}" }
    selection = { text = "${h r.crust}", background = "${h r.accent}" }

    [colors.normal]
    black   = "${h (builtins.elemAt r.ansi 0)}"
    red     = "${h (builtins.elemAt r.ansi 1)}"
    green   = "${h (builtins.elemAt r.ansi 2)}"
    yellow  = "${h (builtins.elemAt r.ansi 3)}"
    blue    = "${h (builtins.elemAt r.ansi 4)}"
    magenta = "${h (builtins.elemAt r.ansi 5)}"
    cyan    = "${h (builtins.elemAt r.ansi 6)}"
    white   = "${h (builtins.elemAt r.ansi 7)}"

    [colors.bright]
    black   = "${h (builtins.elemAt r.ansi 8)}"
    red     = "${h (builtins.elemAt r.ansi 9)}"
    green   = "${h (builtins.elemAt r.ansi 10)}"
    yellow  = "${h (builtins.elemAt r.ansi 11)}"
    blue    = "${h (builtins.elemAt r.ansi 12)}"
    magenta = "${h (builtins.elemAt r.ansi 13)}"
    cyan    = "${h (builtins.elemAt r.ansi 14)}"
    white   = "${h (builtins.elemAt r.ansi 15)}"
  '';

  # --- wezterm runtime theme file (lua fragment that defines the scheme) -----
  # Returns a table merged into the wezterm config via dofile in extraConfig.
  weztermTheme =
    let
      a = r.ansi;
      luaList = lib.concatMapStringsSep ", " (cV: "\"${h cV}\"");
      ansi = luaList (lib.sublist 0 8 a);
      brights = luaList (lib.sublist 8 8 a);
    in
    ''
      -- Generated by modules/config/colors (default) / scripts/theme (runtime).
      -- Theme: ${defaultTheme} / ${defaultFlavor} / ${defaultAccent}
      return {
        colors = {
          foreground = "${h r.text}",
          background = "${h r.crust}",
          cursor_bg = "${h r.accent}",
          cursor_fg = "${h r.crust}",
          cursor_border = "${h r.accent}",
          selection_fg = "${h r.crust}",
          selection_bg = "${h r.accent}",
          ansi = { ${ansi} },
          brights = { ${brights} },
        },
      }
    '';

  # --- tmux runtime theme file (colors for the Catppuccin-style status bar) ----
  # Defines the @thm_* tmux variables the static status bar in
  # modules/config/tmux references lazily (matches scripts/theme output).
  tmuxTheme =
    let
      c = v: "#${v}";
      # Named accent hues (catppuccin-style), falling back to ANSI-derived values
      # so non-catppuccin themes still get sensible module colors.
      named =
        let
          ac = r.accents;
          fallback = k: f: ac.${k} or f;
        in
        {
          red = fallback "red" (builtins.elemAt r.ansi 1);
          maroon = fallback "maroon" (builtins.elemAt r.ansi 9);
          green = fallback "green" (builtins.elemAt r.ansi 2);
          yellow = fallback "yellow" (builtins.elemAt r.ansi 3);
          blue = fallback "blue" (builtins.elemAt r.ansi 4);
          sapphire = fallback "sapphire" (builtins.elemAt r.ansi 12);
          sky = fallback "sky" (fallback "teal" (builtins.elemAt r.ansi 6));
          lavender = fallback "lavender" r.base;
        };
    in
    ''
      # Generated by modules/config/colors (default) / scripts/theme (runtime).
      # Theme: ${defaultTheme} / ${defaultFlavor} / ${defaultAccent}
      # Base styles (panes, messages, selection)
      set -g status-style "bg=${c r.base}"
      set -g pane-border-style "fg=${c r.overlay0}"
      set -g pane-active-border-style "fg=${c r.accent}"
      set -g message-style "bg=${c r.surface0},fg=${c r.text}"
      set -g message-command-style "bg=${c r.accent},fg=${c r.base}"
      set -g mode-style "bg=${c r.surface0},fg=${c r.text}"
      set -g clock-mode-colour "${c named.blue}"
      set -g display-panes-colour "${c r.accent}"
      set -g display-panes-active-colour "${c r.text}"
      # Catppuccin-style palette variables (mirror catppuccin/tmux @thm_* naming)
      set -gq @thm_bg "${c r.base}"
      set -gq @thm_fg "${c r.text}"
      set -gq @thm_crust "${c r.crust}"
      set -gq @thm_mantle "${c r.mantle}"
      set -gq @thm_surface_0 "${c r.surface0}"
      set -gq @thm_surface_1 "${c r.surface1}"
      set -gq @thm_surface_2 "${c r.surface2}"
      set -gq @thm_overlay_0 "${c r.overlay0}"
      set -gq @thm_overlay_1 "${c r.overlay1}"
      set -gq @thm_overlay_2 "${c r.overlay2}"
      set -gq @thm_subtext_0 "${c r.subtext0}"
      set -gq @thm_subtext_1 "${c r.subtext1}"
      set -gq @thm_mauve "${c r.accent}"
      set -gq @thm_red "${c named.red}"
      set -gq @thm_green "${c named.green}"
      set -gq @thm_yellow "${c named.yellow}"
      set -gq @thm_blue "${c named.blue}"
      set -gq @thm_maroon "${c named.maroon}"
      set -gq @thm_sapphire "${c named.sapphire}"
      set -gq @thm_sky "${c named.sky}"
      set -gq @thm_lavender "${c named.lavender}"
    '';

  # --- hyprland runtime theme file (lua fragment, dofiled by extraConfig) -----
  # Returns { active_border, inactive_border } in 0xRRGGBB format. colors.nix
  # (extraConfig) dofiles this on every hyprctl reload so switching needs no
  # rebuild.
  hyprlandTheme =
    let
      x = v: "0x${v}";
    in
    ''
      -- Generated by modules/config/colors (default) / scripts/theme (runtime).
      -- Theme: ${defaultTheme} / ${defaultFlavor} / ${defaultAccent}
      return {
        active_border = "${x r.accent}",
        inactive_border = "${x r.overlay1}",
      }
    '';
in
{
  options.colors = {
    # Full theme database (theme -> title + flavors -> roles + accents).
    themes = mkOption {
      type = types.attrs;
      readOnly = true;
      description = "Generic theme database exposed for build-time consumers";
    };
    # Selected default theme (used only for generating the build-time runtime
    # files; the CLI switches themes at runtime).
    theme = mkOption {
      type = types.str;
      default = defaultTheme;
    };
    flavor = mkOption {
      type = types.str;
      default = defaultFlavor;
    };
    accent = mkOption {
      type = types.str;
      default = defaultAccent;
    };
    # Resolved default roles for any build-time consumer.
    active = mkOption {
      type = types.attrs;
      readOnly = true;
    };
    # Base16 scheme derived from the active selection (for Stylix on both the
    # home and system side; base0D carries the selected accent).
    base16Scheme = mkOption {
      type = types.attrs;
      readOnly = true;
    };
  };

  config = {
    colors.themes = themesJSON;
    colors.active = r;
    colors.base16Scheme = toBase16 r;

    # Machine-readable themes DB for the runtime script (scripts/theme).
    home.file.".local/share/theme-switcher/themes.json" = {
      text = builtins.toJSON themesJSON;
    };

    # Persistent record of the default selection.
    home.file.".local/share/theme-switcher/default" = {
      text = "${defaultTheme} ${defaultFlavor} ${defaultAccent}\n";
    };

    # Initial runtime theme files so the four terminals work out of the box.
    # scripts/theme overwrites these (no rebuild) on ./theme set ...
    home.file.".config/theme-switcher/kitty-theme.conf" = {
      text = kittyTheme;
      force = true;
    };
    home.file.".config/theme-switcher/alacritty-theme.toml" = {
      text = alacrittyTheme;
      force = true;
    };
    home.file.".config/theme-switcher/wezterm-theme.lua" = {
      text = weztermTheme;
      force = true;
    };
    home.file.".config/theme-switcher/tmux-theme.conf" = {
      text = tmuxTheme;
      force = true;
    };
    home.file.".config/theme-switcher/hyprland-theme.lua" = {
      text = hyprlandTheme;
      force = true;
    };

    # The runtime theme files above arrive as read-only store symlinks, but
    # scripts/theme must overwrite them to switch themes. Materialize each into
    # a real writable file on first activation (following the store symlink).
    # On later switches they are already real files, so CLI edits persist.
    home.activation.themeSwitcherWritable =
      lib.hm.dag.entryAfter
        [
          "writeBoundary"
        ]
        ''
          $DRY_RUN_CMD install -d -m 0755 "$HOME/.config/theme-switcher"
          for f in kitty-theme.conf alacritty-theme.toml wezterm-theme.lua tmux-theme.conf hyprland-theme.lua; do
            tgt="$HOME/.config/theme-switcher/$f"
            if [[ -L "$tgt" ]]; then
              $DRY_RUN_CMD cp -fL "$tgt" "$tgt.tmp" && $DRY_RUN_CMD mv -f "$tgt.tmp" "$tgt"
            fi
            # home.file ships these read-only (from the store); the CLI must be
            # able to overwrite them to hot-swap, so make them user-writable.
            if [[ -e "$tgt" ]] && [[ ! -w "$tgt" ]]; then
              $DRY_RUN_CMD chmod u+w "$tgt"
            fi
          done
        '';
  };
}